env:
  DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
  DATABRICKS_HTTP_PATH: ${{ secrets.DATABRICKS_HTTP_PATH }}
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
  DBT_CATALOG: ${{ secrets.DBT_CATALOG }}
  DBT_SCHEMA_DEV: ${{ secrets.DBT_SCHEMA_DEV }}
  DBT_SCHEMA_PROD: ${{ secrets.DBT_SCHEMA_PROD }}
